export const Users = [
  {
    id: 1,
    profilePicture: "/Assets/person/2.jpg.jpg",
    username: "Black Diamond",
  },
  {
    id: 2,
    profilePicture: "/Assets/person/2.jpg.jpg",
    username: "Charity Elias",
  },
  {
    id: 3,
    profilePicture: "/Assets/person/3.jpg.jpg",
    username: "Samuel Spiff",
  },
  {
    id: 4,
    profilePicture: "/Assets/person/4.jpg.jpg",
    username: "Micah Deborah",
  },
  {
    id: 5,
    profilePicture: "/Assets/person/2.jpg.jpg",
    username: "Daniel Veronica",
  },
  {
    id: 6,
    profilePicture: "/Assets/person/4.jpg.jpg",
    username: "Godwin Daniel",
  },
  {
    id: 7,
    profilePicture: "/Assets/person/3.jpg.jpg",
    username: "Isaac Ifeoma",
  },
  {
    id: 8,
    profilePicture: "/Assets/person/2.jpg.jpg",
    username: "Bertrand Rice",
  },
  {
    id: 9,
    profilePicture: "/Assets/person/4.jpg.jpg",
    username: "Smith Jones",
  },
  {
    id: 10,
    profilePicture: "/Assets/person/3.jpg.jpg",
    username: "Johnson Adewale",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Dreams Do Come True. ",
    photo: "/Assets/person/3.jpg.jpg",
    date: "2 mins ago",
    userId: 1,
    likes:100 ,
    comment: 99,
  },
  {
    id: 2,
    desc: "Happy Birthay Ifeoma ",
    photo: "/Assets/posts/4.jpgs.jpg",
    date: "1 day ago",
    userId: 2,
    likes: 66,
    comment: 100,
  },
  {
    id: 3,
    desc: " Rip to Shyness and low self-esteem",
    photo: "/Assets/posts/6.jpgs.jpg",
    date: "10 hours ago",
    userId: 3,
    likes: 66,
    comment: 20,
  },
  {
    id: 4,
    desc: " New gadget",
    photo: "/Assets/ads1.jpg",
    date: "15 mins ago",
    userId: 4,
    likes: 10,
    comment: 5,
  },
  {
    id: 5,
    desc: "Movie Night",
    photo: "/Assets/posts/1.jpgs.jpg",
    date: "20 mins aga",
    userId: 5,
    likes: 80,
    comment: 70,
  },
  {
    id: 6,
    desc: "Always Believe in Yourself ",
    photo: "/Assets/person/4.jpg.jpg",
    date: "10 mins ago",
    userId: 6,
    likes:70,
    comment: 20,
  },
  {
    id: 7,
    desc: "New week New Blessings",
    photo: "/Assets/posts/3.jpgs.jpg",
    date: "22 mins ago",
    userId: 7,
    likes: 44,
    comment: 19,
  },
  {
    id: 8,
    desc: "DDL Music studio ",
    photo: "/Assets/ads.jpg",
    date: "2 days ago",
    userId: 8,
    likes: 17,
    comment: 13,
  },
  {
    id: 9,
    desc: "Dream BIG ",
    photo: "/Assets/person/2.jpg.jpg",
    date: "22 mins ago",
    userId: 9,
    likes:20,
    comment: 18,
  },
  {
    id: 10,
    desc: "Always put a smile on your face ",
    photo: "Assets/person/5.jpg.jpg",
    date: "15 mins ago",
    userId: 10,
    likes: 7,
    comment: 5,
  },
];